### ISSUE TITLE
Issue with Local Storage Reading on Screen Size and Orientation Changes

### ISSUE THREAD

**Issue by yousufansa** [sushinpv/react-secure-storage#30]
I'm currently encountering a puzzling problem in my Next.js web application when attempting to read data from the local storage. This issue specifically manifests itself when there are adjustments to the screen size or changes in the screen's orientation. Despite my efforts, I've been unable to successfully implement a solution using environment keys and their corresponding values, which are intended to bypass encryption related to screen properties.

Version Details:
Next.js: ^13.4.5
react-secure-storage: ^1.2.2

I've utilized the following environment key and value:
`NEXT_PUBLIC_SECURE_LOCAL_STORAGE_DISABLED_KEYS=ScreenPrint`

I would greatly appreciate any insights, guidance, or assistance from the community to help me address this problem effectively. Your input would be immensely valuable, and I thank you in advance for your support.

**Comment by sushinpv** [comment]
In the initial release, this was done on purpose for increased security. However, there has been talk for some time about making the screen print check default opt out and giving users the choice to opt in. 

We haven't decided on the strategy we'll employ moving forward because the major goal of this library is to provide the highest level of safety for local storage, and we don't want to make any compromises there. 

We have checked on the issue which you have mentioned and it seems like, NextJs uses build binding for process.env values, 

Which means 

`process.env.NEXT_PUBLIC_SECURE_LOCAL_STORAGE_DISABLED_KEYS` is valid,
But 

`let KEY = "NEXT_PUBLIC_SECURE_LOCAL_STORAGE_DISABLED_KEYS"`
`process.env[KEY]` is invalid, 

This issue has been fixed on your latest version 1.3.0

Thanks for reporting this issue!

**Comment by yousufansa** [comment]
Hi [Sushin Pv](https://github.com/sushinpv),

Thank you for your prompt response.

I have updated to the latest version, but unfortunately, the problem persists. It's important to note that this issue isn't isolated to Next.js. I've also encountered the same problem in a React app while using the key-value pair REACT_APP_SECURE_LOCAL_STORAGE_DISABLED_KEYS=ScreenPrint. Additionally, I've observed that the REACT_APP_SECURE_LOCAL_STORAGE_HASH_KEY doesn't seem to be functioning as expected.

Your continued assistance in resolving this matter would be greatly appreciated.

**Comment by sushinpv** [comment]
@yousufansa Please have a look at this example which I have created,https://github.com/sushinpv/nextjs-react-secure-storage-example. This is working as expected.

Please let me know if its works for you or not!

**Comment by sushinpv** [comment]
@yousufansa 

Thanks for providing the screen video of the problem statement, The library is working as expected.

In your case, When you change the view to responsive view, there few options we need to take care.

When you enable responsive view in Mozilla Firefox by default, your Dimension selection will be set to Response, which means that you are simulating the same browser by adjusting the screen's width and height. In this case, we are simply changing the screen size; the library will continue to function as intended because it is designed to generate unique hash keys for each type of browser.

However, Mozilla will alter the browser's characteristics, including the user agent, when you switch the Dimension selection to any of the pre-existing selections. For the library this is a different browser not the same browser which it encrypt and saved the data into local storage and as expected it will not decrypt the values.

In-case of Chrome, It will change the UserAgent immediately when you switch to responsive design, irrespective of any selection.

But this will not impact the normal user! Why ? Resizing the window outside the responsive view will not cause any issue, All the browser properties will remain the same.

Please have a look at the video I have attached for more clarity.
https://raw.githubusercontent.com/sushinpv/nextjs-react-secure-storage-example/main/example/screen-record.mp4
High Quality Version ( Please check the MOV file ) : https://github.com/sushinpv/nextjs-react-secure-storage-example/tree/main/example

There are two approaches you can take, 

First option is, You proceed as it is, because this is the expected behavior of the library, this will not make any issue for the normal user, ( Resizing the window outside the responsive view will not cause any issue, All the browser properties will remain the same )

Second option is only for the development build you can add the following code, `NEXT_PUBLIC_SECURE_LOCAL_STORAGE_DISABLED_KEYS=ScreenPrint|UserAgent|Plugins`, This will keep the browser fingerprint consistent even when you switch between responsive selection, But this not recommend for the production build, Use this only to speed up your development process. 

Hope this will help you out!

**Comment by yousufansa** [comment]
@sushinpv 

I wanted to thank you for your response and for explaining the situation so well. Your explanation about how the library behaves in different browser scenarios, especially in responsive views, really helped me understand what was going on.

The video you shared and your detailed description clarified why the library was behaving the way it was. I now get how changes in browser characteristics can affect the encryption and decryption process.

Your suggestion of two options, one for production and another for development, gave me a clear direction to follow. Your advice made it easier for me to decide how to handle the issue moving forward.

Your help has been incredibly valuable in helping me tackle this challenge. Thanks again for taking the time to address my concerns. Your support has been a big help in getting a grip on the situation.
